[features]
seeds = false
skip-lint = false

[programs.localnet]
identity       = "56eTzHJD2rTaa8gmvWTgd71uTKoRDiBZyDkvYJwZVcRk"
asset_registry = "DgB6YnvAFogS9FN5jfScpCyJAmbmComEifnZa2bY8J4y"
oracle_verify  = "BL6YD7cHz2JKsQBPDu4dNWxCHgh34LBAFW86oqHKDtzQ"
marketplace    = "Dqs8TUwX9PC7iUdpQZffHDjmVs1WyDuHSkX2JsPBdtwY"
insurance      = "8aKuqDi4FYChNmQHMQVgtYXeJFdaX44Fj3aMkX1RjZ2m"

[programs.devnet]
identity       = "56eTzHJD2rTaa8gmvWTgd71uTKoRDiBZyDkvYJwZVcRk"
asset_registry = "DgB6YnvAFogS9FN5jfScpCyJAmbmComEifnZa2bY8J4y"
oracle_verify  = "BL6YD7cHz2JKsQBPDu4dNWxCHgh34LBAFW86oqHKDtzQ"
marketplace    = "Dqs8TUwX9PC7iUdpQZffHDjmVs1WyDuHSkX2JsPBdtwY"
insurance      = "8aKuqDi4FYChNmQHMQVgtYXeJFdaX44Fj3aMkX1RjZ2m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
